CREATE DATABASE WebShop

USE WebShop

CREATE TABLE Category
(
	CategoryID INT	PRIMARY KEY IDENTITY(1,1),
	CategoryName VARCHAR(100),
	CategoryImageUrl VARCHAR(MAX),
	IsActive BIT,
	CreatedDate DATETIME
)

CREATE TABLE MainCategory
(
	MainCategoryID INT	PRIMARY KEY IDENTITY(1,1),
	MainCategoryName VARCHAR(100) NOT NULL,
	IsActive BIT NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Product
(
	ProductID INT PRIMARY KEY IDENTITY(1,1),
	ProductName VARCHAR(100) NOT NULL,
	LongDescription VARCHAR(MAX) NULL,	
	Price DECIMAL(18,2) NOT NULL,
	Quantity INT NOT NULL,
	Size VARCHAR(100) NOT NULL,
	CompanyName VARCHAR(100) NULL,
	CategoryId INT FOREIGN KEY REFERENCES Category(CategoryId) ON DELETE CASCADE NOT NULL,
	SubCategoryId INT NOT NULL,
	Sold INT NULL,
	IsCastomized BIT NOT NULL,
	IsActive BIT NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE ProductImages
(
	ImageID INT	PRIMARY KEY IDENTITY(1,1),
	ImageUrl VARCHAR(MAX) NULL,
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	DefaultImage BIT NULL,
)

CREATE TABLE Roles
(
	RoleID INT	PRIMARY KEY IDENTITY(1,1),
	RoleName VARCHAR(50) NOT NULL	
)


CREATE TABLE Users
(
	UserID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	Username VARCHAR(50) NULL UNIQUE,
	Mobile VARCHAR(50) NULL,
	Email VARCHAR(50) NULL,
	Address VARCHAR(MAX) NULL,
	PostCode VARCHAR(50) NULL,
	Password VARCHAR(50) NULL,
	ImageUrl VARCHAR(MAX) NULL,
	RoleID INT FOREIGN KEY REFERENCES Roles(RoleID) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE ProductReview
(
	ReviewID INT	PRIMARY KEY IDENTITY(1,1),
	Rating INT NOT NULL,
	Comment VARCHAR(MAX) NULL,
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Wishlist
(
	WishlistID INT	PRIMARY KEY IDENTITY(1,1),	
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Cart
(
	CartID INT	PRIMARY KEY IDENTITY(1,1),	
	ProductId INT FOREIGN KEY REFERENCES Product(ProductId) ON DELETE CASCADE NOT NULL,
	Quantity INT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Contact
(
	ContactID INT	PRIMARY KEY IDENTITY(1,1),	
	Name VARCHAR(50) NULL,
	Email VARCHAR(50) NULL,
	Subject VARCHAR(200) NULL,
	Message VARCHAR(MAX) NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE Payment
(
	PaymentID INT	PRIMARY KEY IDENTITY(1,1),	
	Name VARCHAR(50) NULL,
	CardNo VARCHAR(50) NULL,
	ExpirtDate VARCHAR(50) NULL,
	CvvNo INT NULL,
	Address VARCHAR(MAX) NULL,
	PaymentMode VARCHAR(50) NULL
)

CREATE TABLE Orders
(
	OrdelDetailID INT	PRIMARY KEY IDENTITY(1,1),
	OrderNo VARCHAR(MAX) NULL,
	ProductID INT FOREIGN KEY REFERENCES Product(ProductID) ON DELETE CASCADE NOT NULL,
	Quantity INT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE NOT NULL,
	Status VARCHAR(50) NULL,
	PaymentID INT FOREIGN KEY REFERENCES Payment(PaymentID) ON DELETE CASCADE NOT NULL,
	OrderDate DATETIME NOT NULL,
	IsCancel BIT NOT NULL DEFAULT 0
)

CREATE TABLE Company
(
	CompanyID INT	PRIMARY KEY IDENTITY(1,1),
	CompanyName VARCHAR(100),
	CategoryImageUrl VARCHAR(MAX),
	IsActive BIT,
	CreatedDate DATETIME
)


